### ISSUE TITLE
aur package

### ISSUE THREAD

**Issue by walkthetalk** [cbernardo/kicad3Dmodels#1]
Hello, I'm using archlinux, can we expect a aur package for your project?

**Comment by cbernardo** [comment]
Hi,
 I do not make any packages for distribution; there are too many versions of Linux to package for.  I use Debian and I don't even create packages for that. However, if package maintainers wish to provide a package for their system I'm happy to help with any issues with building and running the software.
Regards,Cirilo

```
  From: Yi Qingliang <notifications@github.com>
```

 To: cbernardo/kicad3Dmodels kicad3Dmodels@noreply.github.com 
 Sent: Wednesday, September 16, 2015 6:18 PM
 Subject: [kicad3Dmodels] aur package (#1)

Hello, I'm using archlinux, can we expect a aur package for your project?—
